name: GitHub Actions After Push Into Develop Branch
on:
  push:
    branches:
      - develop
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run:  npm run lint
      - name: Run tests
        run: npm test